MyBookShop/MyBookShop/Components/TopBooksViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MyBookShop.Components
{
    public class TopBooksViewComponent:ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

MyBookShop/MyBookShop/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MyBookShop.Models;


namespace MyBookShop.Controllers
{
    public class HomeController : Controller
    {
        public ViewResult Index()
        {
            ViewBag.Type = new BookModel() {id=1,BookName="C#" };
            ViewData["BookDetails"] = new BookModel() {id=5,BookName="React Js" };
            return View();
        }
        public ViewResult AboutUs()
        {
            return View();
        }
        [ViewData]
        public string Address { get; set; }
        public ViewResult ContactUs()
        {
            Address = "Solapur";
            return View();
        }

    }
}

MyBookShop/MyBookShop/Views/Home/AboutUs.cshtml
@{
    ViewData["Title"] = "About Us";
}


<h1>About Us Page</h1>

MyBookShop/MyBookShop/Views/Home/ContactUs.cshtml
@{
    ViewData["Title"] = "Contact Us";
}


<h1>Contact Us Page</h1>
@ViewData["Address"]

MyBookShop/MyBookShop/Views/Home/Index.cshtml
@{ 
    var details = ViewData["BookDetails"] as BookModel;
}
@{ 
    ViewData["Title"] = "Home";
}

@*<h1>Home Page</h1>
<hr />
ID : @ViewBag.Type.id
<br />
Bookname : @ViewBag.Type.BookName
<hr />
Id: @details.id
<br />
Bookname :@details.BookName*@
<div class="py-5 bg-light">
    <div class="container">
        <h3 class="h3">Top books</h3>
        @await Component.InvokeAsync("TopBooks", new { count = 3 })
        
        @*<vc:top-books count="6" ></vc:top-books>*@

    </div>
</div>